### ISSUE TITLE
Issue with compiling language-javascript

### ISSUE THREAD

**Issue by Jyothsnasrinivas** [typelead/eta-hackage#109]
I get the following exception. Most likely has something to do with `happy`.
```
Configuring library for language-javascript-0.6.0.11..
Preprocessing library for language-javascript-0.6.0.11..
Exception in thread "main" java.lang.NullPointerException
	at eta.runtime.storage.Block.fillCache(Block.java:155)
	at eta.runtime.storage.CachedBlock.setBlock(CachedBlock.java:38)
	at eta.runtime.io.MemoryManager.getBlockSlow(MemoryManager.java:103)
	at eta.runtime.io.MemoryManager.getBlock(MemoryManager.java:96)
	at eta.runtime.io.MemoryManager.get(MemoryManager.java:124)
	at main.Parser.$recBinding0(Parser.hs)
	at main.Parser.$LhappyDoAction$1(Parser.hs:111)
	at main.Parser$sat$31.apply1(Parser.hs)
	at main.Lexer$f29$1.thunkEnter(Lexer.lhs)
	at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:19)
	at eta.runtime.thunk.Thunk.apply1(Thunk.java:150)
	at main.Lexer$sat$77.apply1(Lexer.lhs)
	at main.Lexer.$wa(Lexer.lhs)
	at main.Lexer$$wa.apply3(Lexer.lhs)
	at eta.runtime.apply.PAPSlow.apply(PAPSlow.java:43)
	at eta.runtime.apply.PAPSlow.apply1(PAPSlow.java:172)
	at main.Lexer.$wa(Lexer.lhs)
	at main.Parser.$wa1(Parser.hs)
	at main.Parser$sat$36.apply1(Parser.hs)
	at eta.runtime.thunk.Thunk.apply1(Thunk.java:150)
        ....
        .....
```

**Comment by rahulmutt** [comment]
Should be fixed now (was needed for Purescript)
