### ISSUE TITLE
lens-aeson examples throw IllegalStateExceptions

### ISSUE THREAD

**Issue by mmisamore** [typelead/eta-hackage#120]
# Description
lens-aeson examples are throwing runtime exceptions.

# Steps to Reproduce
1. Add build-depends for lens and lens-aeson to a new project .cabal file
2. etlas repl
3. import Control.Lens
4. import Data.Aeson.Lens
5.  "[1, \\"x\\"]" ^? nth 0 . _Number  
or
"42" ^? _Integer

# Expected 
Just 1.0
or
Just 42

# Actual
```
Prelude Data.Aeson.Lens Control.Lens Main>  "[1, \"x\"]" ^? nth 0 . _Number
*** Exception: java.lang.RuntimeException: Failed during evalStmt of Eta REPL expression
	at eta.serv.REPLClassLoader.evalStmt(REPLClassLoader.java:253)
	at eta.serv.Utils.evalStmt(Utils.java:32)
	at main.eta.serv.Run$sat$21.applyV(Run.hs:61)
	at eta.runtime.exception.Exception.catch_(Exception.java:132)
	at main.eta.serv.Run$sat$20.applyV(Run.hs:181)
	at main.eta.serv.Run.$La4$1(Run.hs:166)
	at main.eta.serv.Run$sat$23.applyV(Run.hs)
	at eta.runtime.exception.Exception.unmaskAsyncExceptions(Exception.java:94)
	at main.eta.serv.Run$sat$19.applyV(Run.hs:125)
	at eta.runtime.exception.Exception.catch_(Exception.java:132)
	at main.eta.serv.Run$sat$18.applyV(Run.hs)
	at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:125)
	at eta.runtime.stg.Capability.schedule(Capability.java:254)
	at eta.runtime.concurrent.WorkerThread.run(WorkerThread.java:16)
Caused by: java.lang.RuntimeException: Failed during evalIOInternal of Eta REPL expression
	at eta.serv.REPLClassLoader.evalIOInternal(REPLClassLoader.java:381)
	at eta.serv.REPLClassLoader.evalStmt(REPLClassLoader.java:246)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at eta.serv.REPLClassLoader.evalIOInternal(REPLClassLoader.java:379)
	... 14 more
Caused by: java.lang.IllegalStateException: The trampoline function expects a thunk and not a function [class aeson.data.aeson.types.internal.datacons.Success extends class aeson.data.aeson.types.internal.tycons.Result]
	at eta.runtime.stg.Stg.trampoline(Stg.java:87)
	at lens_aeson.data.aeson.Lens.$fAsNumber_ByteString3(Lens.hs:386)
	at lens_aeson.data.aeson.Lens$$fAsNumber_ByteString3.apply1(Lens.hs)
	at profunctors.data.profunctor.Unsafe$sat$1.thunkEnter(Unsafe.hs:169)
	at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:19)
	at base.data.Either.$fFunctor_Either_$cfmap(Either.hs:130)
	at base.data.Either$$fFunctor_Either_$cfmap.apply2(Either.hs:130)
	at eta.runtime.apply.PAP1_1.apply1(PAP1_1.java:62)
	at eta.runtime.thunk.Thunk.apply1(Thunk.java:151)
	at profunctors.data.profunctor.Unsafe$sat.thunkEnter(Unsafe.hs:169)
	at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:19)
	at lens_aeson.data.aeson.Lens$sat$261.apply1(Lens.hs)
	at profunctors.data.profunctor.Unsafe.$fProfunctor_ZLzmzgZR_$cdimap(Unsafe.hs:169)
	at profunctors.data.profunctor.Unsafe$$fProfunctor_ZLzmzgZR_$cdimap.apply4(Unsafe.hs:169)
	at eta.runtime.apply.PAPSlow.apply(PAPSlow.java:53)
	at eta.runtime.apply.PAPSlow.apply1(PAPSlow.java:179)
	at eta.runtime.thunk.Thunk.apply1(Thunk.java:151)
	at profunctors.data.profunctor.Unsafe$sat.thunkEnter(Unsafe.hs:169)
	at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:19)
	at eta.runtime.stg.Closure.evaluateTail(Closure.java:33)
	at base.data.functor.Const.$fFunctor_Const2(Const.hs:66)
	at base.data.functor.Const$$fFunctor_Const2.apply2(Const.hs)
	at eta.runtime.apply.PAP1_1.apply1(PAP1_1.java:62)
	at eta.runtime.thunk.Thunk.apply1(Thunk.java:151)
	at profunctors.data.profunctor.Unsafe.$fProfunctor_ZLzmzgZR_$cdimap(Unsafe.hs:169)
	at profunctors.data.profunctor.Unsafe$$fProfunctor_ZLzmzgZR_$cdimap.apply4(Unsafe.hs:169)
	at eta.runtime.apply.PAPSlow.apply(PAPSlow.java:53)
	at eta.runtime.apply.PAPSlow.apply1(PAPSlow.java:179)
	at eta.runtime.thunk.Thunk.apply1(Thunk.java:151)
	at profunctors.data.profunctor.Unsafe$sat.thunkEnter(Unsafe.hs:169)
	at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:19)
	at eta.runtime.stg.Closure.evaluateTail(Closure.java:33)
	at base.data.functor.Const.$fFunctor_Const2(Const.hs:66)
	at base.data.functor.Const$$fFunctor_Const2.apply2(Const.hs)
	at eta.runtime.apply.PAP1_1.apply1(PAP1_1.java:62)
	at eta.runtime.thunk.Thunk.apply1(Thunk.java:151)
	at profunctors.data.profunctor.Unsafe.$fProfunctor_ZLzmzgZR_$cdimap(Unsafe.hs:169)
	at profunctors.data.profunctor.Unsafe$$fProfunctor_ZLzmzgZR_$cdimap.apply4(Unsafe.hs:169)
	at eta.runtime.apply.PAPSlow.apply(PAPSlow.java:53)
	at eta.runtime.apply.PAPSlow.apply1(PAPSlow.java:179)
	at eta.runtime.thunk.Thunk.apply1(Thunk.java:151)
	at profunctors.data.profunctor.Unsafe$sat.thunkEnter(Unsafe.hs:169)
	at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:19)
	at eta.runtime.stg.Closure.evaluateTail(Closure.java:33)
	at base.data.functor.Const.$fFunctor_Const2(Const.hs:66)
	at base.data.functor.Const$$fFunctor_Const2.apply2(Const.hs)
	at eta.runtime.apply.PAP1_1.apply1(PAP1_1.java:62)
	at eta.runtime.thunk.Thunk.apply1(Thunk.java:151)
	at profunctors.data.profunctor.Unsafe.$fProfunctor_ZLzmzgZR_$cdimap(Unsafe.hs:169)
	at profunctors.data.profunctor.Unsafe$$fProfunctor_ZLzmzgZR_$cdimap.apply4(Unsafe.hs:169)
	at eta.runtime.apply.PAPSlow.apply(PAPSlow.java:53)
	at eta.runtime.apply.PAPSlow.apply1(PAPSlow.java:179)
	at eta.runtime.apply.PAPSlow.apply2(PAPSlow.java:212)
	at eta.runtime.thunk.Thunk.apply2(Thunk.java:161)
	at lens.control.lens.Fold.$La12$1(Fold.hs:1266)
	at lens.control.lens.Fold.zcz3fU(Fold.hs:1266)
	at lens.control.lens.Fold$zcz3fU.apply2(Fold.hs:1266)
	at interactive.EtaRepl1_3$it0.thunkEnter(Interactive.hs)
	at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:19)
	at base.ghc.Show.$fShow_Maybe_$cshow(Show.hs:190)
	at base.ghc.Show$sat$492.apply1(Show.hs)
	at base.system.IO$sat.thunkEnter(IO.hs:279)
	at eta.runtime.thunk.SingleEntryThunk.evaluate(SingleEntryThunk.java:20)
	at base.ghc.io.handle.Text.hPutStr3(Text.hs:558)
	at base.ghc.io.handle.Text.hPutStr2(Text.hs:550)
	at base.system.IO.print1(IO.hs:265)
	at base.system.IO.print(IO.hs:279)
	at base.system.IO$print.apply2V(IO.hs:279)
	at eta.runtime.apply.PAPSlow.apply(PAPSlow.java:71)
	at eta.runtime.apply.PAPSlow.applyV(PAPSlow.java:119)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at base.ghc.Base.thenIO1(Base.hs:1335)
	at base.ghc.Base.thenIO(Base.hs:1335)
	at base.ghc.Base$thenIO.apply2V(Base.hs:1335)
	at eta.runtime.apply.PAPSlow.apply(PAPSlow.java:71)
	at eta.runtime.apply.PAPSlow.applyV(PAPSlow.java:119)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at eta.runtime.exception.Exception.unmaskAsyncExceptions(Exception.java:94)
	at base.control.exception.Base$sat$25.applyV(Base.hs)
	at eta.runtime.exception.Exception.catch_(Exception.java:132)
	at base.control.exception.Base$sat$22.applyV(Base.hs:226)
	at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:45)
	at base.control.exception.Base.bracket1(Base.hs:228)
	at base.system.Environment.withArgs1(Environment.hs:156)
	at base.system.Environment.withArgs(Environment.hs:153)
	at base.system.Environment$withArgs.apply2V(Environment.hs:153)
	at eta.runtime.apply.PAPSlow.apply(PAPSlow.java:71)
	at eta.runtime.apply.PAPSlow.applyV(PAPSlow.java:119)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at eta.runtime.exception.Exception.unmaskAsyncExceptions(Exception.java:94)
	at base.control.exception.Base$sat$25.applyV(Base.hs)
	at eta.runtime.exception.Exception.catch_(Exception.java:132)
	at base.control.exception.Base$sat$22.applyV(Base.hs:226)
	at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:45)
	at base.control.exception.Base.bracket1(Base.hs:228)
	at base.system.Environment.withProgName1(Environment.hs:170)
	at base.system.Environment.withProgName(Environment.hs:168)
	at base.system.Environment$withProgName.apply2V(Environment.hs:168)
	at eta.runtime.apply.PAPSlow.apply(PAPSlow.java:71)
	at eta.runtime.apply.PAPSlow.applyV(PAPSlow.java:119)
	at eta.runtime.stg.Closures$EvalIO.enter(Closures.java:150)
	at eta.runtime.stg.Capability.schedule(Capability.java:254)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:210)
	at eta.runtime.Runtime.evalIO(Runtime.java:380)
	... 19 more
```

# Environment
1.  etlas --version
etlas version 1.5.0.0
compiled using version 2.1.0.0 of the etlas-cabal library 
2. The Eta Programming Language Compiler, Version 0.8.6b2, Git Revision e42f73dcfa407c0f80394240911a488d85c7199a
3. Mac OS X: Darwin Michaels-MacBook-Pro.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64

**Comment by mmisamore** [comment]
Thanks @rahulmutt! I see that it is trying to trampoline via an Eta Hackage patch here, but I'm not sure why it would fail in this specific case: https://github.com/typelead/eta-hackage/blob/master/patches/aeson-1.2.4.0.patch. As you said, maybe the aeson patch is trampolining on the wrong expression.

I'll pull down the eta compiler repo and see if I can get it to compile, because this looks like it would be educational.

**Comment by jneira** [comment]
If i remember correctly i got that error when using trampoline in a class instance method impl, so it seems internally it is not represented by a `Thunk` like normal functions

**Comment by rahulmutt** [comment]
Great. Btw, if you have successfully source installed the `master` version of Eta, a fast way to test changes to the runtime can be done with:

```
stack exec eta-build -- rts-clean
```

All future Eta project compilations will use the new version of the runtime with your changes (unless you're using Gradle to compile your Eta projects, in which case you should wipe out `~/.gradle/caches/etlas` before doing that step).

**Comment by rahulmutt** [comment]
Should be resolved after https://github.com/typelead/eta/pull/896 submitted by the OP.
