### ISSUE TITLE
package tasty not running

### ISSUE THREAD

**Issue by tittoassini** [typelead/eta-hackage#56]
Compiles but won't run, error (on macOS Sierra):

Exception in thread "main" java.lang.NoSuchMethodError: eta.runtime.concurrent.Concurrent.labelThread(Leta/runtime/stg/StgContext;Leta/runtime/stg/TSO;J)Leta/runtime/stg/Closure;
	at tasty.test.tasty.Parallel$sat_sMTT.enter(Unknown Source)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.apply.Function.applyPV(Function.java:117)
	at base.ghc.Foreign$$wa1.enter(Unknown Source)
	at base.ghc.Foreign$$wa3_sDAHO.enter(Unknown Source)
	at base.ghc.Foreign$sat_sDAIF.enter(Unknown Source)
	at eta.runtime.apply.PAP.apply(PAP.java:31)
	at eta.runtime.apply.PAP.applyV(PAP.java:41)
	at eta.runtime.thunk.Thunk.applyV(Thunk.java:121)
	at eta.runtime.exception.Exception.unmaskAsyncExceptions(Exception.java:90)
	at base.ghc.IO$sat_s8Y4ZZ.enter(Unknown Source)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at eta.runtime.exception.Exception.catch_(Exception.java:135)
	at base.ghc.IO$sat_s8Y5C.enter(Unknown Source)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:41)
	at base.ghc.IO$bracket1.enter(Unknown Source)
	at base.ghc.Foreign$charIsRepresentable3.enter(Unknown Source)
	at tasty.test.tasty.Parallel$runInParallel1.enter(Unknown Source)
	at tasty.test.tasty.Run$sat_s21YJ.enter(Unknown Source)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at tasty.test.tasty.Run$launchTestTree4.enter(Unknown Source)
	at tasty.test.tasty.Run$launchTestTree1.enter(Unknown Source)
	at tasty.test.tasty.Ingredients$sat_s235L.enter(Unknown Source)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at tasty.test.tasty.CmdLine$defaultMainWithIngredients1.enter(Unknown Source)
	at main.Main$main1.enter(Unknown Source)
	at main.Main$DZCmain.enter(Unknown Source)
	at eta.runtime.apply.Function.applyV(Function.java:16)
	at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:96)
	at eta.runtime.stg.Capability.schedule(Capability.java:150)
	at eta.runtime.stg.Capability.scheduleClosure(Capability.java:97)
	at eta.runtime.Runtime.evalLazyIO(Runtime.java:189)
	at eta.runtime.Runtime.main(Runtime.java:182)
	at eta.main.main(Unknown Source)

**Comment by rahulmutt** [comment]
Fixed on `master`. If you could upload the sample project, I can test out the other stuff too.

**Comment by tittoassini** [comment]
Tasty now seems to be hanging.

Tested after updating to latest eta version from git repo, running 'etlas test' on the https://github.com/Quid2/flat project.

**Comment by rahulmutt** [comment]
Ok then it seems to be related to the test-framework issue. I'll look into it.
